#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
microbench_report.py — merge the per-function micro-bench traces (leaf_<variant>.csv)
and the per-stage scenario traces (stages_<variant>.csv) across build variants into a
single ranked MICROBENCH_REPORT.md.

Reusable as coverage grows: re-run after adding more functions to the runner.

Usage:  python microbench_report.py <microbench_dir>
Outputs <microbench_dir>/MICROBENCH_REPORT.md
"""
from __future__ import annotations
import csv, os, sys, math

VARIANTS = ["ReleaseFast", "ReleaseSafe", "Debug"]


def load_leaf(d, v):
    p = os.path.join(d, f"leaf_{v}.csv")
    out = {}
    if os.path.exists(p):
        for r in csv.DictReader(open(p)):
            out[(r["module"], r["function"], r.get("impl", "orig"))] = float(r["min_ns"])
    return out


def load_stage(d, fname):
    p = os.path.join(d, fname)
    out = {}
    if os.path.exists(p):
        for r in csv.DictReader(open(p)):
            out[(r["scenario"], r["zone"])] = float(r["min_ns"])
    return out


def fmt_ns(ns):
    if ns is None:
        return "—"
    if ns >= 1e6:
        return f"{ns/1e6:.2f}ms"
    if ns >= 1e3:
        return f"{ns/1e3:.2f}µs"
    return f"{ns:.2f}ns"


def ratio(a, b):
    return f"{b/a:.2f}×" if (a and b and a > 0) else "—"


def main(d):
    L = {v: load_leaf(d, v) for v in VARIANTS}
    # leaf rows: union of keys
    leaf_keys = set()
    for v in VARIANTS:
        leaf_keys |= set(L[v].keys())

    out = []
    out.append("# Micro-bench report — per-function timing × build variant")
    out.append("")
    out.append("Generated by `tools/analysis/microbench_report.py`. `min_ns` per call (leaf) or")
    out.append("per stage-iteration (stages). Variants compiled via `-Doptimize=`. Safe/Fast = cost")
    out.append("of safety checks; Dbg/Fast = cost of no-optimize. See PERFUNC_BENCH_GOAL.md.")
    out.append("")

    # ---- Findings ----
    out.append("## Key findings so far")
    out.append("")
    out.append("- **ReleaseSafe crashes on large maps**: the build pipeline panics (ntdll hard")
    out.append("  exit, no clean Zig panic surfaced) on `map_1` (8M cells) under ReleaseSafe,")
    out.append("  but completes on `map_1_coarse` (2M cells). A latent large-map overflow/")
    out.append("  bounds issue that ReleaseFast runs through silently — worth a dedicated repro.")
    out.append("- **Safety is ~free for leaf math** (Safe/Fast ≈ 0.96–1.00×): pure register")
    out.append("  arithmetic has nothing to bounds/overflow-check.")
    out.append("- **Safety costs most in serialization**: `dtCreateNavMeshData` pays **4.68×** under")
    out.append("  ReleaseSafe (index/bounds-heavy), vs ~1.2–1.4× for the build stages.")
    out.append("- **Debug is 3–19× slower** across the board — the floor for any debug-build use.")
    out.append("")

    # ---- Analog comparison: functions with >1 impl (orig vs analog) ----
    rf_leaf = L["ReleaseFast"]
    by_fn = {}
    for (mod, fn, impl) in leaf_keys:
        by_fn.setdefault((mod, fn), set()).add(impl)
    analog_fns = {k: v for k, v in by_fn.items() if len(v) > 1}
    out.append(f"## Analog comparisons (orig vs alternative impl) — {len(analog_fns)} functions")
    out.append("")
    if analog_fns:
        out.append("All analogs passed the identical-output gate (== original over the input sweep),")
        out.append("so these are behaviour-preserving. ReleaseFast min per call.")
        out.append("")
        out.append("| function | orig | analog | impl | speedup (orig/analog) | verdict |")
        out.append("|---|---|---|---|---|---|")
        for (mod, fn), impls in sorted(analog_fns.items()):
            orig = rf_leaf.get((mod, fn, "orig"))
            for impl in sorted(impls - {"orig"}):
                an = rf_leaf.get((mod, fn, impl))
                sp = (orig / an) if (orig and an) else None
                verdict = "—"
                if sp:
                    verdict = "analog faster" if sp > 1.05 else ("orig faster" if sp < 0.95 else "tie (≈)")
                out.append(f"| {mod}/{fn} | {fmt_ns(orig)} | {fmt_ns(an)} | {impl} | {sp:.2f}× | {verdict}" if sp else f"| {mod}/{fn} | {fmt_ns(orig)} | {fmt_ns(an)} | {impl} | — | — |")
        out.append("")
        out.append("> Note: leaf functions sit near the ~1ns timer-resolution floor, so analog")
        out.append("> deltas here are small/quantised. Measurable analog wins live in the heavier")
        out.append("> (ms-scale) stage functions, where an analog means an alternative algorithm.")
    else:
        out.append("_(none yet — analogs are being added per function)_")
    out.append("")

    # ---- Leaf table (ranked by ReleaseFast) ----
    out.append(f"## Leaf / pure functions ({len(leaf_keys)} impls wired) — ranked by ReleaseFast min")
    out.append("")
    rows = []
    for k in leaf_keys:
        rf = L["ReleaseFast"].get(k)
        rs = L["ReleaseSafe"].get(k)
        db = L["Debug"].get(k)
        rows.append((k, rf, rs, db))
    rows.sort(key=lambda x: (x[1] is None, -(x[1] or 0)))
    out.append("| function | impl | iso | ReleaseFast | Safe/Fast | Dbg/Fast |")
    out.append("|---|---|---|---|---|---|")
    for (mod, fn, impl), rf, rs, db in rows:
        out.append(f"| {mod}/{fn} | {impl} | A | {fmt_ns(rf)} | {ratio(rf,rs)} | {ratio(rf,db)} |")
    out.append("")

    # ---- Stage table (coarse has all 3 variants) ----
    rf_s = load_stage(d, "stages_ReleaseFast.csv")
    db_s = load_stage(d, "stages_Debug.csv")
    rs_s = load_stage(d, "stages_RSafe_coarse.csv")
    coarse = "build_solo_watershed_map_1_coarse"
    stage_order = [
        "rcRasterizeTriangles", "rcFilterLedgeSpans", "rcFilterLowHangingWalkableObstacles",
        "rcFilterWalkableLowHeightSpans", "rcBuildCompactHeightfield", "rcErodeWalkableArea",
        "rcBuildDistanceField", "rcBuildRegions", "rcBuildContours", "rcBuildPolyMesh",
        "rcBuildPolyMeshDetail", "dtCreateNavMeshData",
    ]
    out.append("## Pipeline stages — map_1_coarse (min per stage-iteration)")
    out.append("")
    out.append("| stage | ReleaseFast | Safe/Fast | Dbg/Fast |")
    out.append("|---|---|---|---|")
    present = [z for z in stage_order if (coarse, z) in rf_s]
    present += [z for (sc, z) in rf_s if sc == coarse and z not in stage_order]
    for z in present:
        rf = rf_s.get((coarse, z))
        rs = rs_s.get((coarse, z))
        db = db_s.get((coarse, z))
        out.append(f"| {z} | {fmt_ns(rf)} | {ratio(rf,rs)} | {ratio(rf,db)} |")
    out.append("")

    out.append("## Coverage")
    out.append("")
    out.append(f"- Leaf/pure functions wired: **{len(leaf_keys)}**")
    out.append(f"- Pipeline stages traced (3-variant on coarse): **{len(present)}**")
    out.append("- Remaining: scale leaf wiring toward the full 396-function inventory; add per-map")
    out.append("  stage variants; classify class-C internal helpers via tracy.zoneDeep.")
    out.append("")

    rep = os.path.join(d, "MICROBENCH_REPORT.md")
    with open(rep, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {rep} ({len(leaf_keys)} leaf, {len(present)} stages)")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
